config/routes.rb
Rails.application.routes.draw do

  root "rooms#index"

  resources :rooms do
    resources :messages
  end

  resources :blogs do
    resources :blog_messages
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :blog_messages
end

app/models/blog_message.rb
class BlogMessage < ApplicationRecord
  belongs_to :blog
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room

  after_create_commit { broadcast_append_to room }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/blog_messages_controller.rb
class BlogMessagesController < ApplicationController
  before_action :set_blog_message, only: [:show, :edit, :update, :destroy]

  # GET /blog_messages
  # GET /blog_messages.json
  def index
    @blog_messages = BlogMessage.all
  end

  # GET /blog_messages/1
  # GET /blog_messages/1.json
  def show
  end

  # GET /blog_messages/new
  def new
    @blog_message = BlogMessage.new
  end

  # GET /blog_messages/1/edit
  def edit
  end

  # POST /blog_messages
  # POST /blog_messages.json
  def create
    @blog_message = BlogMessage.new(blog_message_params)

    respond_to do |format|
      if @blog_message.save
        format.html { redirect_to @blog_message, notice: 'Blog message was successfully created.' }
        format.json { render :show, status: :created, location: @blog_message }
      else
        format.html { render :new }
        format.json { render json: @blog_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_messages/1
  # PATCH/PUT /blog_messages/1.json
  def update
    respond_to do |format|
      if @blog_message.update(blog_message_params)
        format.html { redirect_to @blog_message, notice: 'Blog message was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_message }
      else
        format.html { render :edit }
        format.json { render json: @blog_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_messages/1
  # DELETE /blog_messages/1.json
  def destroy
    @blog_message.destroy
    respond_to do |format|
      format.html { redirect_to blog_messages_url, notice: 'Blog message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_message
      @blog_message = BlogMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_message_params
      params.require(:blog_message).permit(:body, :blog_id)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[ new create ]

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.create!(message_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @room }
    end
  end

  private
  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.create!(room_params)
    redirect_to @room, notice: 'Room was successfully created.'
  end

  def update
    @room.update!(room_params)
    redirect_to @room, notice: 'Room was successfully updated.'
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_messages_helper.rb
module BlogMessagesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/blog_messages/_blog_messages.html.erb
<div id="<%= dom_id blog_message %>">
  <%= blog_message.created_at.to_s(:short) %> :: <%= blog_message.body %>
</div>

app/views/blog_messages/new.html.erb
<h1>새 메세지</h1>

<%= form_with(model: [@blog_messages.blog, @blog_messages]) do |form| %>
  <%= form.text_field :body %>
  <%= form.submit "Send" %>
<% end %>

app/views/blog_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @blog_message.body %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @blog_message.blog_id %>
</p>

<%= link_to 'Edit', edit_blog_message_path(@blog_message) %> |
<%= link_to 'Back', blog_messages_path %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

<%= turbo_frame_tag "new_blog", src: new_blog_path, target: "_top" %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= turbo_frame_tag "new_blog" do %>
  <%= render 'form', blog: @blog %>
<% end %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<div id="messages">
  <%= render @blog.blog_messages %>
</div>

<%= render @blog.blog_messages %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HotwireFirstshot</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= yield :head %>

  <%= turbo_include_tags %>
  <%= stimulus_include_tags %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <%= message.created_at.to_s(:short) %> :: <%= message.content %>
</div>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.append "messages", @message %>

app/views/messages/new.html.erb
<h1>새 메세지</h1>

<%= turbo_frame_tag "new_message", target: "_top" do %>
  <%= form_with(
        model: [@message.room, @message],
        data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset" }) do |form| %>
    <div class="field">
      <%= form.text_field :content %>
      <%= form.submit "Send" %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', @message.room %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<p id="<%= dom_id room %>">
  <strong>Name:</strong>
  <%= room.name %>
</p>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= turbo_frame_tag "room" do %>
  <%= render 'form', room: @room %>
<% end %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.id %> | <%= room.name %></td>

      <td><%= link_to 'Show', room %></td>

      <td><%= link_to 'Edit', edit_room_path(room) %></td>

      <td><%= link_to 'Destroy', room_path(room.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<br>
<%= turbo_frame_tag "new_room", src: new_room_path, target: "_top" %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= turbo_frame_tag "new_room" do %>
  <%= render 'form', room: @room %>
<% end %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_stream_from @room %>

<%= turbo_frame_tag "room" do %>
  <%= render @room %>

  <p>
    <%= link_to 'Edit', edit_room_path(@room) %> |
    <%= link_to 'Back', rooms_path, "data-turbo-frame": "_top" %>
  </p>
<% end %>

<div id="messages">
  <%= render @room.messages %>
</div>

<%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "_top" %>